### PR TITLE
PLUG-146 Updates for luvit 2.0

### PR DESCRIPTION
**Pull request by thirty8super**
Update version numbers.  
Change run command to pick up new luvit2.0
Fix broken error msg handling for luvit2.0
Set default poll to 5 secs.

FYI My editor auto-strips trailing spaces so ignore the changes with removed trailing space.

### CODE REVIEW

**Comment by kchenhal** [comment]
looks good, but a lot of diffs are just ending space, which make reading the changes a little bit difficult.

**Comment by thirty8super** [comment]
Yeah hence my FYI.  I don't know what type of crazy editor JDG used in the first place that added those extra spaces...

**Comment by kchenhal** [comment]
It is no harm. +1

**Comment by gokumar** [comment]
LGTM too

**Comment by craigching** [comment]
removing trailing spaces? You must use emacs! 💯

**Comment by JoeBmc** [comment]
Looks good.

**Pull request merged**
